---
name: Deploy Firestore Rules

on:
  push:
    branches:
      - main
    paths:
      - "firebase/firestore.rules"
      - "firebase/firestore.indexes.json"
  workflow_dispatch:

jobs:
  deploy-rules:
    name: Deploy Firestore Rules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create service account key file
        run: >
          echo '${{ secrets.FIREBASE_ADMIN_API }}' >
          $HOME/service-account-key.json

      - name: Set Google Application Credentials
        run: >
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account-key.json"
          >> $GITHUB_ENV

      - name: Deploy Firestore rules
        run: >
          firebase deploy --only firestore:rules
          --project systemcraft-bms

      - name: Deploy Firestore indexes
        run: >
          firebase deploy --only firestore:indexes
          --project systemcraft-bms

      - name: Clean up service account key
        if: always()
        run: rm -f $HOME/service-account-key.json
